[global]
ioengine=rbd
clientname=admin
pool=cephrbd_data
rbdname=rbd01
direct=1
thread
group_reporting
iodepth=16
runtime=100
bs=4K
per_job_logs=1

[seq-write-4k]
numjobs=1
name="seq-write-4k"
size=256M
rw=write

[seq-read-4k]
numjobs=1
name="seq-read-4k"
size=256M
rw=read

[rand-write-4k]
numjobs=1
name="rand-write-4k"
size=256M
rw=randwrite

[rand-read-4k]
numjobs=1
name="rand-read-4k"
size=256M
rw=randread

[rand-read-write-4k]
numjobs=1
name="rand-rw-4k"
size=256M
rw=randrw
rwmixread=70
